export let albums_of_all_time = [
 {
  title: "Prince - Sign O' the Times",
  cover_url: "6472-sign-o-the-times-1.jpg",
  date: "March 31, 1987",
  genres: ["Contemporary R&B", "Synth Funk", "Pop Rock"],
  critic_score: "100",
  num_reviews: "8",
 },
 {
  title: "Fleetwood Mac - Rumours",
  cover_url: "rumours-1.jpg",
  date: "February 4, 1977",
  genres: ["Pop Rock", "Soft Rock"],
  critic_score: "100",
  num_reviews: "7",
 },
 {
  title:
   "David Bowie - The Rise and Fall of Ziggy Stardust and the Spiders from Mars",
  cover_url:
   "5598-the-rise-and-fall-of-ziggy-stardust-and-the-spiders-from-mars_162706.jpg",
  date: "June 16, 1972",
  genres: ["Glam Rock", "Pop Rock"],
  critic_score: "100",
  num_reviews: "7",
 },
 {
  title: "Led Zeppelin - Led Zeppelin IV",
  cover_url: "led-zeppelin-iv.jpg",
  date: "November 8, 1971",
  genres: ["Hard Rock"],
  critic_score: "100",
  num_reviews: "7",
 },
 {
  title: "Pixies - Doolittle",
  cover_url: "doolittle-1.jpg",
  date: "April 18, 1989",
  genres: ["Indie Rock", "Alternative Rock"],
  critic_score: "100",
  num_reviews: "7",
 },
 {
  title: "The Beatles - Revolver",
  cover_url: "4092-revolver-1.jpg",
  date: "August 5, 1966",
  genres: ["Pop Rock", "Psychedelic Pop"],
  critic_score: "100",
  num_reviews: "7",
 },
 {
  title: "Paul Simon - Graceland",
  cover_url: "6511-graceland.jpg",
  date: "August 12, 1986",
  genres: ["Pop Rock", "Singer-Songwriter"],
  critic_score: "100",
  num_reviews: "6",
 },
 {
  title: "Bob Dylan - Blood on the Tracks",
  cover_url: "5656-blood-on-the-tracks_221858.jpg",
  date: "January 20, 1975",
  genres: ["Singer-Songwriter", "Folk Rock"],
  critic_score: "100",
  num_reviews: "6",
 },
 {
  title: "Bob Dylan - Highway 61 Revisited",
  cover_url: "5604-highway-61-revisited_212703.jpg",
  date: "August 30, 1965",
  genres: ["Folk Rock", "Singer-Songwriter"],
  critic_score: "100",
  num_reviews: "6",
 },
 {
  title: "The Beatles - Sgt. Pepper's Lonely Hearts Club Band",
  cover_url: "sgt-peppers-lonely-hearts-club-band-1.jpg",
  date: "May 26, 1967",
  genres: ["Psychedelic Pop", "Pop Rock"],
  critic_score: "100",
  num_reviews: "6",
 },
 {
  title: "The Beatles - Rubber Soul",
  cover_url: "rubber-soul-1.jpg",
  date: "December 3, 1965",
  genres: ["Pop Rock"],
  critic_score: "100",
  num_reviews: "6",
 },
 {
  title: "The Beatles - Abbey Road",
  cover_url: "abbey-road-1.jpg",
  date: "September 26, 1969",
  genres: ["Pop Rock"],
  critic_score: "100",
  num_reviews: "6",
 },
 {
  title: "Patti Smith - Horses",
  cover_url: "7217-horses.jpg",
  date: "November 10, 1975",
  genres: ["Art Rock", "Proto-punk", "Singer-Songwriter", "Glam Rock"],
  critic_score: "100",
  num_reviews: "5",
 },
 {
  title: "Elvis Presley - Elvis Presley",
  cover_url: "6420-elvis-presley-1.jpg",
  date: "March 23, 1956",
  genres: ["Rockabilly", "Rock & Roll"],
  critic_score: "100",
  num_reviews: "5",
 },
 {
  title: "Big Star - Third",
  cover_url: "6315-thirdsister-lovers-1.jpg",
  date: "March 18, 1978",
  genres: ["Pop Rock"],
  critic_score: "100",
  num_reviews: "5",
 },
 {
  title: "Joni Mitchell - Court and Spark",
  cover_url: "6086-court-and-spark_235650.jpg",
  date: "January 17, 1974",
  genres: ["Singer-Songwriter", "Folk Pop"],
  critic_score: "100",
  num_reviews: "5",
 },
 {
  title: "Joni Mitchell - Blue",
  cover_url: "6084-blue-1.jpg",
  date: "June 22, 1971",
  genres: ["Singer-Songwriter", "Contemporary Folk"],
  critic_score: "100",
  num_reviews: "5",
 },
 {
  title: "Leonard Cohen - Songs of Leonard Cohen",
  cover_url: "6079-songs-of-leonard-cohen-1.jpg",
  date: "December 27, 1967",
  genres: ["Contemporary Folk", "Singer-Songwriter"],
  critic_score: "100",
  num_reviews: "5",
 },
 {
  title: "Miles Davis - Kind of Blue",
  cover_url: "6040-kind-of-blue-2.jpg",
  date: "August 17, 1959",
  genres: ["Modal Jazz", "Cool Jazz"],
  critic_score: "100",
  num_reviews: "5",
 },
 {
  title: "The Stooges - Fun House",
  cover_url: "6035-funhouse-1.jpg",
  date: "July 7, 1970",
  genres: ["Garage Rock", "Proto-punk", "Hard Rock"],
  critic_score: "100",
  num_reviews: "5",
 },
 {
  title: "Santana - Abraxas",
  cover_url: null,
  date: "September 23, 1970",
  genres: ["Psychedelic Rock", "Latin Rock"],
  critic_score: "100",
  num_reviews: "5",
 },
 {
  title: "Stevie Wonder - Songs in the Key of Life",
  cover_url: "5600-songs-in-the-key-of-life_145510.jpg",
  date: "September 28, 1976",
  genres: ["Soul"],
  critic_score: "100",
  num_reviews: "5",
 },
 {
  title: "The Beach Boys - Pet Sounds",
  cover_url: "pet-sounds-1.jpg",
  date: "May 16, 1966",
  genres: ["Baroque Pop"],
  critic_score: "100",
  num_reviews: "5",
 },
 {
  title: "Metallica - Master of Puppets",
  cover_url: "master-of-puppets-1.jpg",
  date: "March 3, 1986",
  genres: ["Thrash Metal"],
  critic_score: "100",
  num_reviews: "5",
 },
 {
  title: "Pink Floyd - The Dark Side of the Moon",
  cover_url: "4204-the-dark-side-of-the-moon-1.jpg",
  date: "March 1, 1973",
  genres: ["Art Rock", "Progressive Rock"],
  critic_score: "99",
  num_reviews: "7",
 },
];
