export let albums_of_all_time = [
 {
  artist: "Prince",
  album_title: "Sign O' the Times",
  cover_url: "6472-sign-o-the-times-1.jpg",
  date: "March 31, 1987",
  genres: ["Contemporary R&B", "Synth Funk", "Pop Rock"],
  critic_score: "100",
  num_reviews: "8",
 },
 {
  artist: "Fleetwood Mac",
  album_title: "Rumours",
  cover_url: "rumours-1.jpg",
  date: "February 4, 1977",
  genres: ["Pop Rock", "Soft Rock"],
  critic_score: "100",
  num_reviews: "7",
 },
 {
  artist: "David Bowie",
  album_title: "The Rise and Fall of Ziggy Stardust and the Spiders from Mars",
  cover_url:
   "5598-the-rise-and-fall-of-ziggy-stardust-and-the-spiders-from-mars_162706.jpg",
  date: "June 16, 1972",
  genres: ["Glam Rock", "Pop Rock"],
  critic_score: "100",
  num_reviews: "7",
 },
 {
  artist: "Led Zeppelin",
  album_title: "Led Zeppelin IV",
  cover_url: "led-zeppelin-iv.jpg",
  date: "November 8, 1971",
  genres: ["Hard Rock"],
  critic_score: "100",
  num_reviews: "7",
 },
 {
  artist: "Pixies",
  album_title: "Doolittle",
  cover_url: "doolittle-1.jpg",
  date: "April 18, 1989",
  genres: ["Indie Rock", "Alternative Rock"],
  critic_score: "100",
  num_reviews: "7",
 },
 {
  artist: "The Beatles",
  album_title: "Revolver",
  cover_url: "4092-revolver-1.jpg",
  date: "August 5, 1966",
  genres: ["Pop Rock", "Psychedelic Pop"],
  critic_score: "100",
  num_reviews: "7",
 },
 {
  artist: "Paul Simon",
  album_title: "Graceland",
  cover_url: "6511-graceland.jpg",
  date: "August 12, 1986",
  genres: ["Pop Rock", "Singer-Songwriter"],
  critic_score: "100",
  num_reviews: "6",
 },
 {
  artist: "Bob Dylan",
  album_title: "Blood on the Tracks",
  cover_url: "5656-blood-on-the-tracks_221858.jpg",
  date: "January 20, 1975",
  genres: ["Singer-Songwriter", "Folk Rock"],
  critic_score: "100",
  num_reviews: "6",
 },
 {
  artist: "Bob Dylan",
  album_title: "Highway 61 Revisited",
  cover_url: "5604-highway-61-revisited_212703.jpg",
  date: "August 30, 1965",
  genres: ["Folk Rock", "Singer-Songwriter"],
  critic_score: "100",
  num_reviews: "6",
 },
 {
  artist: "The Beatles",
  album_title: "Sgt. Pepper's Lonely Hearts Club Band",
  cover_url: "sgt-peppers-lonely-hearts-club-band-1.jpg",
  date: "May 26, 1967",
  genres: ["Psychedelic Pop", "Pop Rock"],
  critic_score: "100",
  num_reviews: "6",
 },
 {
  artist: "The Beatles",
  album_title: "Rubber Soul",
  cover_url: "rubber-soul-1.jpg",
  date: "December 3, 1965",
  genres: ["Pop Rock"],
  critic_score: "100",
  num_reviews: "6",
 },
 {
  artist: "The Beatles",
  album_title: "Abbey Road",
  cover_url: "abbey-road-1.jpg",
  date: "September 26, 1969",
  genres: ["Pop Rock"],
  critic_score: "100",
  num_reviews: "6",
 },
 {
  artist: "Patti Smith",
  album_title: "Horses",
  cover_url: "7217-horses.jpg",
  date: "November 10, 1975",
  genres: ["Art Rock", "Proto-punk", "Singer-Songwriter", "Glam Rock"],
  critic_score: "100",
  num_reviews: "5",
 },
 {
  artist: "Elvis Presley",
  album_title: "Elvis Presley",
  cover_url: "6420-elvis-presley-1.jpg",
  date: "March 23, 1956",
  genres: ["Rockabilly", "Rock & Roll"],
  critic_score: "100",
  num_reviews: "5",
 },
 {
  artist: "Big Star",
  album_title: "Third",
  cover_url: "6315-thirdsister-lovers-1.jpg",
  date: "March 18, 1978",
  genres: ["Pop Rock"],
  critic_score: "100",
  num_reviews: "5",
 },
 {
  artist: "Joni Mitchell",
  album_title: "Court and Spark",
  cover_url: "6086-court-and-spark_235650.jpg",
  date: "January 17, 1974",
  genres: ["Singer-Songwriter", "Folk Pop"],
  critic_score: "100",
  num_reviews: "5",
 },
 {
  artist: "Joni Mitchell",
  album_title: "Blue",
  cover_url: "6084-blue-1.jpg",
  date: "June 22, 1971",
  genres: ["Singer-Songwriter", "Contemporary Folk"],
  critic_score: "100",
  num_reviews: "5",
 },
 {
  artist: "Leonard Cohen",
  album_title: "Songs of Leonard Cohen",
  cover_url: "6079-songs-of-leonard-cohen-1.jpg",
  date: "December 27, 1967",
  genres: ["Contemporary Folk", "Singer-Songwriter"],
  critic_score: "100",
  num_reviews: "5",
 },
 {
  artist: "Miles Davis",
  album_title: "Kind of Blue",
  cover_url: "6040-kind-of-blue-2.jpg",
  date: "August 17, 1959",
  genres: ["Modal Jazz", "Cool Jazz"],
  critic_score: "100",
  num_reviews: "5",
 },
 {
  artist: "The Stooges",
  album_title: "Fun House",
  cover_url: "6035-funhouse-1.jpg",
  date: "July 7, 1970",
  genres: ["Garage Rock", "Proto-punk", "Hard Rock"],
  critic_score: "100",
  num_reviews: "5",
 },
 {
  artist: "Santana",
  album_title: "Abraxas",
  cover_url: null,
  date: "September 23, 1970",
  genres: ["Psychedelic Rock", "Latin Rock"],
  critic_score: "100",
  num_reviews: "5",
 },
 {
  artist: "Stevie Wonder",
  album_title: "Songs in the Key of Life",
  cover_url: "5600-songs-in-the-key-of-life_145510.jpg",
  date: "September 28, 1976",
  genres: ["Soul"],
  critic_score: "100",
  num_reviews: "5",
 },
 {
  artist: "The Beach Boys",
  album_title: "Pet Sounds",
  cover_url: "pet-sounds-1.jpg",
  date: "May 16, 1966",
  genres: ["Baroque Pop"],
  critic_score: "100",
  num_reviews: "5",
 },
 {
  artist: "Metallica",
  album_title: "Master of Puppets",
  cover_url: "master-of-puppets-1.jpg",
  date: "March 3, 1986",
  genres: ["Thrash Metal"],
  critic_score: "100",
  num_reviews: "5",
 },
 {
  artist: "Pink Floyd",
  album_title: "The Dark Side of the Moon",
  cover_url: "4204-the-dark-side-of-the-moon-1.jpg",
  date: "March 1, 1973",
  genres: ["Art Rock", "Progressive Rock"],
  critic_score: "99",
  num_reviews: "7",
 },
 {
  artist: "Nick Drake",
  album_title: "Five Leaves Left",
  cover_url: "6068-five-leaves-left.jpg",
  date: "July 3, 1969",
  genres: ["Chamber Folk", "Singer-Songwriter"],
  critic_score: "99",
  num_reviews: "5",
 },
 {
  artist: "Steely Dan",
  album_title: "Aja",
  cover_url: "9039-aja.jpg",
  date: "September 23, 1977",
  genres: ["Jazz-Rock", "Yacht Rock"],
  critic_score: "99",
  num_reviews: "6",
 },
 {
  artist: "Public Enemy",
  album_title: "It Takes a Nation of Millions to Hold Us Back",
  cover_url: "6331-it-takes-a-nation-of-millions-to-hold-us-back.jpg",
  date: "April 14, 1988",
  genres: ["Hardcore Hip Hop", "Conscious Hip Hop", "East Coast Hip Hop"],
  critic_score: "99",
  num_reviews: "6",
 },
 {
  artist: "Eno",
  album_title: "Another Green World",
  cover_url: "6031-another-green-world.jpg",
  date: "September 1, 1975",
  genres: ["Art Rock"],
  critic_score: "99",
  num_reviews: "6",
 },
 {
  artist: "Curtis Mayfield",
  album_title: "Superfly",
  cover_url: "13232-superfly_143236.jpg",
  date: "July 11, 1972",
  genres: ["Funk", "Soul"],
  critic_score: "98",
  num_reviews: "5",
 },
 {
  artist: "Michael Jackson",
  album_title: "Off the Wall",
  cover_url: "6267-off-the-wall-1.jpg",
  date: "August 10, 1979",
  genres: ["Disco"],
  critic_score: "98",
  num_reviews: "5",
 },
 {
  artist: "Grateful Dead",
  album_title: "Workingman's Dead",
  cover_url: "5651-workingmans-dead_113029.jpg",
  date: "June 14, 1970",
  genres: ["Folk Rock", "Country Rock"],
  critic_score: "98",
  num_reviews: "5",
 },
 {
  artist: "Led Zeppelin",
  album_title: "Led Zeppelin",
  cover_url: "led-zeppelin-1.jpg",
  date: "January 12, 1969",
  genres: ["Hard Rock", "Blues Rock"],
  critic_score: "98",
  num_reviews: "5",
 },
 {
  artist: "Carole King",
  album_title: "Tapestry",
  cover_url: "7514-tapestry_155158.jpg",
  date: "February 10, 1971",
  genres: ["Soft Rock", "Singer-Songwriter", "Pop Rock"],
  critic_score: "98",
  num_reviews: "5",
 },
 {
  artist: "David Bowie",
  album_title: "Hunky Dory",
  cover_url: "6330-hunky-dory-1.jpg",
  date: "December 17, 1971",
  genres: ["Glam Rock", "Pop Rock", "Art Rock"],
  critic_score: "98",
  num_reviews: "5",
 },
 {
  artist: "Elvis Costello & The Attractions",
  album_title: "This Year's Model",
  cover_url: "6310-this-years-model.jpg",
  date: "March 17, 1978",
  genres: ["New Wave", "Power Pop"],
  critic_score: "98",
  num_reviews: "5",
 },
 {
  artist: "Stevie Wonder",
  album_title: "Innervisions",
  cover_url: "5601-innervisions_145613.jpg",
  date: "August 3, 1973",
  genres: ["Soul"],
  critic_score: "98",
  num_reviews: "5",
 },
 {
  artist: "U2",
  album_title: "Achtung Baby",
  cover_url: "achtung-baby-1.jpg",
  date: "November 18, 1991",
  genres: ["Alternative Rock", "Pop Rock"],
  critic_score: "98",
  num_reviews: "5",
 },
 {
  artist: "Pixies",
  album_title: "Surfer Rosa",
  cover_url: null,
  date: "March 21, 1988",
  genres: ["Indie Rock", "Alternative Rock"],
  critic_score: "98",
  num_reviews: "7",
 },
 {
  artist: "The Beatles",
  album_title: "The Beatles",
  cover_url: "the-beatles-1.jpg",
  date: "November 22, 1968",
  genres: ["Rock", "Pop Rock"],
  critic_score: "98",
  num_reviews: "8",
 },
 {
  artist: "Marvin Gaye",
  album_title: "What's Going On",
  cover_url: "5593-whats-going-on_145542.jpg",
  date: "May 21, 1971",
  genres: ["Soul"],
  critic_score: "97",
  num_reviews: "7",
 },
 {
  artist: "Talking Heads",
  album_title: "Remain in Light",
  cover_url: "remain-in-light-2.jpg",
  date: "October 8, 1980",
  genres: ["New Wave", "Post-Punk"],
  critic_score: "97",
  num_reviews: "7",
 },
 {
  artist: "Wu-Tang Clan",
  album_title: "Enter The Wu-Tang (36 Chambers)",
  cover_url: "enter-wu-tang-36-chambers-4.jpg",
  date: "November 9, 1993",
  genres: ["Hardcore Hip Hop", "Boom Bap", "East Coast Hip Hop"],
  critic_score: "97",
  num_reviews: "7",
 },
 {
  artist: "The Beatles",
  album_title: "A Hard Day's Night",
  cover_url: "a-hard-days-night-1.jpg",
  date: "July 10, 1964",
  genres: ["Pop Rock", "Merseybeat"],
  critic_score: "97",
  num_reviews: "6",
 },
 {
  artist: "Bruce Springsteen",
  album_title: "Born in the U.S.A.",
  cover_url: "born-in-the-usa.jpg",
  date: "June 4, 1984",
  genres: ["Heartland Rock"],
  critic_score: "97",
  num_reviews: "6",
 },
 {
  artist: "Led Zeppelin",
  album_title: "Led Zeppelin II",
  cover_url: "led-zeppelin-ii-1.jpg",
  date: "October 22, 1969",
  genres: ["Hard Rock", "Blues Rock"],
  critic_score: "97",
  num_reviews: "6",
 },
 {
  artist: "Willie Nelson",
  album_title: "Red Headed Stranger",
  cover_url: "19874-red-headed-stranger.jpg",
  date: "May 1, 1975",
  genres: ["Outlaw Country"],
  critic_score: "97",
  num_reviews: "5",
 },
 {
  artist: "Bruce Springsteen",
  album_title: "Born to Run",
  cover_url: "born-to-run.jpg",
  date: "August 25, 1975",
  genres: ["Heartland Rock"],
  critic_score: "97",
  num_reviews: "5",
 },
 {
  artist: "Public Enemy",
  album_title: "Apocalypse 91... The Enemy Strikes Black",
  cover_url: "6808-apocalypse-91-the-enemy-strikes-black.jpg",
  date: "October 3, 1991",
  genres: ["Conscious Hip Hop", "East Coast Hip Hop", "Hardcore Hip Hop"],
  critic_score: "96",
  num_reviews: "5",
 },
 {
  artist: "Michael Jackson",
  album_title: "Thriller",
  cover_url: "6266-thriller-1.jpg",
  date: "November 30, 1982",
  genres: ["Dance-Pop", "Contemporary R&B", "Pop"],
  critic_score: "96",
  num_reviews: "5",
 },
 {
  artist: "George Harrison",
  album_title: "All Things Must Pass",
  cover_url: "6083-all-things-must-pass_104829.jpg",
  date: "November 27, 1970",
  genres: ["Folk Rock", "Pop Rock", "Singer-Songwriter"],
  critic_score: "96",
  num_reviews: "5",
 },
 {
  artist: "Wire",
  album_title: "Pink Flag",
  cover_url: "6047-pink-flag.jpg",
  date: "December 0, 1977",
  genres: ["Art Punk", "Punk Rock"],
  critic_score: "96",
  num_reviews: "5",
 },
 {
  artist: "Miles Davis",
  album_title: "Sketches of Spain",
  cover_url: "6041-sketches-of-spain.jpg",
  date: "July 18, 1960",
  genres: ["Third Stream", "Modal Jazz"],
  critic_score: "96",
  num_reviews: "5",
 },
 {
  artist: "Iggy & The Stooges",
  album_title: "Raw Power",
  cover_url: "6036-raw-power.jpg",
  date: "February 7, 1973",
  genres: ["Proto-punk", "Garage Rock", "Hard Rock"],
  critic_score: "96",
  num_reviews: "5",
 },
 {
  artist: "The Congos",
  album_title: "Heart of the Congos",
  cover_url: "5960-heart-of-the-congos_052010.jpg",
  date: "",
  genres: ["Roots Reggae"],
  critic_score: "96",
  num_reviews: "5",
 },
 {
  artist: "Talking Heads",
  album_title: "Fear of Music",
  cover_url: "5860-fear-of-music-2.jpg",
  date: "August 3, 1979",
  genres: ["Post-Punk", "New Wave", "Art Punk"],
  critic_score: "96",
  num_reviews: "5",
 },
 {
  artist: "Kraftwerk",
  album_title: "Trans Europa Express",
  cover_url: "5786-trans-europe-express-1.jpg",
  date: "March 0, 1977",
  genres: ["Progressive Electronic", "Electronic"],
  critic_score: "96",
  num_reviews: "5",
 },
 {
  artist: "The Band",
  album_title: "The Band",
  cover_url: "the-band-1.jpg",
  date: "September 22, 1969",
  genres: ["Folk Rock", "Country Rock", "Roots Rock"],
  critic_score: "96",
  num_reviews: "5",
 },
 {
  artist: "R.E.M.",
  album_title: "Automatic for the People",
  cover_url: "automatic-for-the-people-1.jpg",
  date: "October 5, 1992",
  genres: ["Alternative Rock", "Pop Rock"],
  critic_score: "96",
  num_reviews: "5",
 },
 {
  artist: "Dr. Dre",
  album_title: "The Chronic",
  cover_url: "the-chronic-1.jpg",
  date: "December 15, 1992",
  genres: ["G-Funk", "Gangsta Rap", "West Coast Hip Hop"],
  critic_score: "96",
  num_reviews: "5",
 },
 {
  artist: "Soundgarden",
  album_title: "Superunknown",
  cover_url: "superunknown.jpg",
  date: "March 8, 1994",
  genres: ["Grunge", "Alternative Rock"],
  critic_score: "96",
  num_reviews: "5",
 },
 {
  artist: "Black Sabbath",
  album_title: "Paranoid",
  cover_url: "5588-paranoid.jpg",
  date: "September 18, 1970",
  genres: ["Heavy Metal", "Hard Rock"],
  critic_score: "96",
  num_reviews: "6",
 },
 {
  artist: "Prince",
  album_title: "Dirty Mind",
  cover_url: "6509-dirty-mind.jpg",
  date: "October 8, 1980",
  genres: ["Pop Rock", "Synth Funk"],
  critic_score: "96",
  num_reviews: "7",
 },
 {
  artist: "JAY-Z",
  album_title: "Reasonable Doubt",
  cover_url: "7008-reasonable-doubt-1.jpg",
  date: "June 25, 1996",
  genres: ["Gangsta Rap", "Boom Bap", "East Coast Hip Hop"],
  critic_score: "96",
  num_reviews: "5",
 },
 {
  artist: "Nick Drake",
  album_title: "Pink Moon",
  cover_url: "5886-pink-moon.jpg",
  date: "February 25, 1972",
  genres: ["Singer-Songwriter", "Contemporary Folk"],
  critic_score: "95",
  num_reviews: "6",
 },
 {
  artist: "David Bowie",
  album_title: "Low",
  cover_url: "5661-low-1.jpg",
  date: "January 14, 1977",
  genres: ["Art Rock", "Ambient"],
  critic_score: "95",
  num_reviews: "6",
 },
 {
  artist: "Massive Attack",
  album_title: "Blue Lines",
  cover_url: "blue-lines-1.jpg",
  date: "April 8, 1991",
  genres: ["Trip Hop"],
  critic_score: "95",
  num_reviews: "6",
 },
 {
  artist: "Bruce Springsteen",
  album_title: "Tunnel of Love",
  cover_url: "6291-tunnel-of-love.jpg",
  date: "October 9, 1987",
  genres: ["Pop Rock", "Singer-Songwriter", "Heartland Rock"],
  critic_score: "95",
  num_reviews: "5",
 },
 {
  artist: "Neil Young",
  album_title: "On The Beach",
  cover_url: "5993-on-the-beach.jpg",
  date: "July 16, 1974",
  genres: ["Country Rock", "Folk Rock", "Singer-Songwriter"],
  critic_score: "95",
  num_reviews: "5",
 },
 {
  artist: "Tom Waits",
  album_title: "Swordfishtrombones",
  cover_url: "5896-swordfishtrombones.jpg",
  date: "September 1, 1983",
  genres: ["Singer-Songwriter", "Experimental Rock"],
  critic_score: "95",
  num_reviews: "5",
 },
 {
  artist: "Elvis Costello",
  album_title: "My Aim Is True",
  cover_url: "6308-my-aim-is-true-1.jpg",
  date: "July 22, 1977",
  genres: ["New Wave", "Power Pop"],
  critic_score: "95",
  num_reviews: "6",
 },
 {
  artist: "Prince & The Revolution",
  album_title: "Purple Rain",
  cover_url: "6376-purple-rain-3.jpg",
  date: "June 25, 1984",
  genres: ["Synth Funk", "Pop Rock"],
  critic_score: "95",
  num_reviews: "10",
 },
 {
  artist: "Kendrick Lamar",
  album_title: "To Pimp a Butterfly",
  cover_url: "29250-to-pimp-a-butterfly-1.jpg",
  date: "March 15, 2015",
  genres: ["Conscious Hip Hop", "Jazz Rap", "West Coast Hip Hop"],
  critic_score: "95",
  num_reviews: "45",
 },
 {
  artist: "Neu!",
  album_title: "Neu!",
  cover_url: "6306-neu.jpg",
  date: "February 0, 1972",
  genres: ["Krautrock"],
  critic_score: "95",
  num_reviews: "6",
 },
 {
  artist: "R.E.M.",
  album_title: "Murmur",
  cover_url: "6101-murmur.jpg",
  date: "April 12, 1983",
  genres: ["Jangle Pop"],
  critic_score: "95",
  num_reviews: "7",
 },
 {
  artist: "AC/DC",
  album_title: "Back in Black",
  cover_url: "back-in-black.jpg",
  date: "July 25, 1980",
  genres: ["Hard Rock"],
  critic_score: "94",
  num_reviews: "7",
 },
 {
  artist: "SAULT",
  album_title: "Earth",
  cover_url: "565468-earth.jpg",
  date: "November 1, 2022",
  genres: ["Neo-Soul"],
  critic_score: "94",
  num_reviews: "5",
 },
 {
  artist: "Kate Bush",
  album_title: "Hounds Of Love",
  cover_url: "6495-hounds-of-love.jpg",
  date: "September 16, 1985",
  genres: ["Art Pop", "Progressive Pop"],
  critic_score: "94",
  num_reviews: "5",
 },
 {
  artist: "Funkadelic",
  album_title: "Maggot Brain",
  cover_url: "6305-maggot-brain-1.jpg",
  date: "July 12, 1971",
  genres: ["Funk Rock", "Psychedelic Soul"],
  critic_score: "94",
  num_reviews: "5",
 },
 {
  artist: "Oasis",
  album_title: "Definitely Maybe",
  cover_url: "definitely-maybe-1.jpg",
  date: "August 30, 1994",
  genres: ["Britpop", "Alternative Rock"],
  critic_score: "94",
  num_reviews: "8",
 },
 {
  artist: "Radiohead",
  album_title: "OK Computer",
  cover_url: "ok-computer-1.jpg",
  date: "May 21, 1997",
  genres: ["Art Rock", "Alternative Rock"],
  critic_score: "94",
  num_reviews: "13",
 },
 {
  artist: "David Crosby",
  album_title: "If I Could Only Remember My Name",
  cover_url: "13074-if-i-could-only-remember-my-name.jpg",
  date: "February 22, 1971",
  genres: ["Folk Rock", "Singer-Songwriter"],
  critic_score: "94",
  num_reviews: "5",
 },
 {
  artist: "Alice in Chains",
  album_title: "Dirt",
  cover_url: null,
  date: "September 29, 1992",
  genres: ["Grunge", "Alternative Metal"],
  critic_score: "94",
  num_reviews: "5",
 },
 {
  artist: "The Beatles",
  album_title: "Help!",
  cover_url: "4094-help-1.jpg",
  date: "August 6, 1965",
  genres: ["Pop Rock"],
  critic_score: "94",
  num_reviews: "5",
 },
 {
  artist: "Tom Petty and the Heartbreakers",
  album_title: "Damn the Torpedoes",
  cover_url: "10646-damn-the-torpedoes.jpg",
  date: "October 19, 1979",
  genres: ["Heartland Rock"],
  critic_score: "94",
  num_reviews: "7",
 },
 {
  artist: "De La Soul",
  album_title: "3 Feet High and Rising",
  cover_url: "6378-3-feet-high-and-rising-1.jpg",
  date: "March 3, 1989",
  genres: ["East Coast Hip Hop", "Conscious Hip Hop"],
  critic_score: "94",
  num_reviews: "6",
 },
 {
  artist: "Brian Eno",
  album_title: "Before and After Science",
  cover_url: "6098-before-and-after-science.jpg",
  date: "December 10, 1977",
  genres: ["Art Rock"],
  critic_score: "94",
  num_reviews: "6",
 },
 {
  artist: "Beastie Boys",
  album_title: "Paul's Boutique",
  cover_url: "pauls-boutique.jpg",
  date: "July 25, 1989",
  genres: ["East Coast Hip Hop"],
  critic_score: "94",
  num_reviews: "6",
 },
 {
  artist: "Anaïs Mitchell",
  album_title: "Hadestown",
  cover_url: "hadestown.jpg",
  date: "March 9, 2010",
  genres: [
   "Americana",
   "Chamber Folk",
   "Chamber Jazz",
   "Contemporary Folk",
   "Alt-Country",
  ],
  critic_score: "94",
  num_reviews: "6",
 },
 {
  artist: "Serge Gainsbourg",
  album_title: "Histoire de Melody Nelson",
  cover_url: "histoire-de-melody-nelson.jpg",
  date: "March 24, 1971",
  genres: ["Art Pop", "French Pop"],
  critic_score: "93",
  num_reviews: "7",
 },
 {
  artist: "Self Esteem",
  album_title: "Prioritise Pleasure",
  cover_url: "388071-prioritise-pleasure-1.jpg",
  date: "October 22, 2021",
  genres: ["Electropop", "Alt-Pop"],
  critic_score: "93",
  num_reviews: "18",
 },
 {
  artist: "Roxy Music",
  album_title: "For Your Pleasure",
  cover_url: "6328-for-your-pleasure-1.jpg",
  date: "March 23, 1973",
  genres: ["Glam Rock", "Art Rock"],
  critic_score: "93",
  num_reviews: "5",
 },
 {
  artist: "Nick Cave and the Bad Seeds",
  album_title: "Ghosteen",
  cover_url: "178735-ghosteen_191130.jpg",
  date: "October 4, 2019",
  genres: ["Ambient Pop", "Singer-Songwriter"],
  critic_score: "93",
  num_reviews: "37",
 },
 {
  artist: "Isaac Hayes",
  album_title: "Hot Buttered Soul",
  cover_url: "6689-hot-buttered-soul_234427.jpg",
  date: "June 0, 1969",
  genres: ["Soul"],
  critic_score: "93",
  num_reviews: "7",
 },
 {
  artist: "Cécile McLorin Salvant",
  album_title: "Dreams and Daggers",
  cover_url: "91670-dreams-and-daggers.jpg",
  date: "September 29, 2017",
  genres: ["Vocal Jazz"],
  critic_score: "93",
  num_reviews: "6",
 },
 {
  artist: "A Guy Called Gerald",
  album_title: "Black Secret Technology",
  cover_url: "24557-black-secret-technology.jpg",
  date: "February 1, 1995",
  genres: ["Jungle", "Drum and Bass"],
  critic_score: "93",
  num_reviews: "6",
 },
 {
  artist: "Kendrick Lamar",
  album_title: "DAMN.",
  cover_url: "76870-damn_184924.jpg",
  date: "April 14, 2017",
  genres: ["Conscious Hip Hop", "West Coast Hip Hop"],
  critic_score: "93",
  num_reviews: "43",
 },
 {
  artist: "The Zombies",
  album_title: "Odessey and Oracle",
  cover_url: "6014-odessey-and-oracle.jpg",
  date: "April 19, 1968",
  genres: ["Psychedelic Pop", "Baroque Pop", "Pop Rock"],
  critic_score: "93",
  num_reviews: "5",
 },
 {
  artist: "Green Day",
  album_title: "Dookie",
  cover_url: "dookie-1.jpg",
  date: "February 1, 1994",
  genres: ["Pop Punk"],
  critic_score: "93",
  num_reviews: "7",
 },
 {
  artist: "The Microphones",
  album_title: "Mount Eerie",
  cover_url: "mount-eerie-2.jpg",
  date: "January 21, 2003",
  genres: ["Avant-Folk", "Psychedelic Folk"],
  critic_score: "93",
  num_reviews: "5",
 },
];
// const updatedAlbums = albums_of_all_time.map((album) => {
//  // Split the title into artist and album title
//  const [artist, albumTitle] = album.title.split(" - ", 2);
//
//  // Create a new object with separated artist and album title
//  return {
//   artist: artist,
//   album_title: albumTitle,
//   cover_url: album.cover_url,
//   date: album.date,
//   genres: album.genres,
//   critic_score: album.critic_score,
//   num_reviews: album.num_reviews,
//  };
// });
//
// // Convert the array to a string in JavaScript format
// const jsString = JSON.stringify(updatedAlbums, null, 2);
//
// // Print the result
// console.log(jsString);
